"""Every constant LAT uses comes from ``lisaconstants`` (Mike 2026-10-08).

Python reads ``lisatools.utils.constants`` (imports ``lisaconstants``); C/C++/
CUDA reads the committed ``cutils/lisaconstants_values.h`` generated by
``lisatools.utils.lisaconstants_header``. This pins (1) the committed header
against the installed ``lisaconstants``, (2) the Python module, and (3) that
none of the old hard-coded literals has crept back into the package source.
"""
import os
import re
import unittest

import lisaconstants as lc

from lisatools.utils import constants as K
from lisatools.utils import lisaconstants_header as H

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKG = os.path.join(ROOT, "src", "lisatools")
HEADER = os.path.join(PKG, "cutils", "lisaconstants_values.h")

#: literals that used to stand in for lisaconstants values somewhere in LAT
#: (old LIGO-library / older-lisaconstants numbers, a rounded year)
OLD_LITERALS = (
    "31558149.763545603",      # year, 8e-9 s off ASTRONOMICAL_YEAR
    "3.15581497635456e7",
    "1.3271244210789466e",     # old GM_sun
    "1.988546954961461",       # old M_sun
    "3.154e7",                 # rounded year (galactic response)
    "3.3356409519815204e-09",  # 1/c written out
)


class HeaderTest(unittest.TestCase):
    def test_committed_header_matches_the_installed_lisaconstants(self):
        with open(HEADER) as fh:
            got = H.parse(fh.read())
        want = H.expected_values()
        self.assertEqual(set(got), set(want))
        for k, v in want.items():
            self.assertEqual(got[k], v, k)      # exact: repr round-trips

    def test_the_header_text_is_what_the_generator_writes(self):
        with open(HEADER) as fh:
            self.assertEqual(fh.read(), H.render())

    def test_derived_values_are_the_python_module_values(self):
        want = H.expected_values()
        self.assertEqual(want["LISACONSTANTS_MTSUN"], K.MTSUN_SI)
        self.assertEqual(want["LISACONSTANTS_MRSUN"], K.MRSUN_SI)


class PythonModuleTest(unittest.TestCase):
    def test_constants_module_is_lisaconstants(self):
        self.assertEqual(K.C_SI, lc.SPEED_OF_LIGHT)
        self.assertEqual(K.YRSID_SI, lc.ASTRONOMICAL_YEAR)
        self.assertEqual(K.MSUN_SI, lc.SOLAR_MASS)
        self.assertEqual(K.GMSUN, lc.SOLAR_MASS_PARAMETER)
        self.assertEqual(K.PC_SI, lc.PARSEC)
        self.assertEqual(K.AU_SI, lc.ASTRONOMICAL_UNIT)

    def test_no_old_hard_coded_literal_in_the_package(self):
        hits = []
        for root, _, files in os.walk(PKG):
            if "__pycache__" in root:
                continue
            for fn in files:
                if not fn.endswith((".py", ".h", ".hh", ".hpp", ".cu", ".cxx")):
                    continue
                path = os.path.join(root, fn)
                with open(path, errors="replace") as fh:
                    for i, line in enumerate(fh, 1):
                        code = re.split(r"#|//", line, maxsplit=1)[0]
                        for lit in OLD_LITERALS:
                            if lit in code:
                                hits.append(f"{os.path.relpath(path, ROOT)}:{i}: {lit}")
        self.assertEqual(hits, [])


if __name__ == "__main__":
    unittest.main()
